updated validEnvironment location

diff --git a/bin/sdagent-supportconfig b/bin/sdagent-supportconfig
--- a/bin/sdagent-supportconfig
+++ b/bin/sdagent-supportconfig
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-SVER='1.0.38'
+SVER='1.0.40'
 
 ##############################################################################
 # sdagent-suportconfig - SCA Agent Worker for Supportconfig Archives
@@ -9,7 +9,7 @@ SVER='1.0.38'
 # Description:  A process forked by the sdagent to analyze a supportconfig 
 #               archive. Supportconfig archives can be from any server.
 # Runs on:      Agent Server
-# Modified:     2018 Jan 08
+# Modified:     2018 Jan 09
 #
 ##############################################################################
 #
@@ -1165,10 +1165,6 @@ main() {
 	REPORT_DATE=$(date "+%Y-%m-%d %T")
 	title
 	msg debug "LOGLEVEL=$LOGLEVEL"
-	if ! validEnvironment; then
-		finishWorker Error "Invalid environment"
-		exit 20
-	fi
 	msg verbose "PROCESSING" "Archive $ARCHIVE"
 	RUN_TIME_START=$(date +%s)
 	ARCHDIR=$(echo $ARCHIVE | sed -e 's/\.t[b,g]z$//;s/\.tar\.bz2$//;s/\.tar\.gz$//')
@@ -1212,6 +1208,10 @@ main() {
 		extractArchive
 		getArchiveInfo
 		patternPreProcessor
+		if ! validEnvironment; then
+			finishWorker Error "Invalid environment"
+			exit 20
+		fi
 		archiveIdentitySQL
 		importArchiveSQL
 		analyzeArchiveStart
